version: '3'
services:
    postgres:
        container_name: postgres
        image: postgres:latest
        volumes:
          - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
        restart: always
        ports:
         - "5432:5432"
        logging:
          options:
            max-size: 1G
    iglu-server:
        container_name: iglu-server
        image: iglu-server:0.3.0
        command: [ "--config", "/snowplow/config/application.conf" ]
        depends_on:
         - postgres
        ports:
         - "8080:8080"
        volumes:
         - "./config/application.conf:/snowplow/config/application.conf"
        logging:
          options:
            max-size: 1G
