apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iglu-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: iglu
    spec:
      containers:
        - name: iglu-server
          image: snowplow-docker-registry.bintray.io/snowplow/iglu-server:0.4.0
          command: [ "/bin/sh", "-c", "/usr/bin/java -jar /snowplow/bin/iglu-server-0.4.0.jar --config /snowplow/config/application.conf" ]
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /snowplow/config
      volumes:
        - name: config-volume
          configMap:
            name: iglu-config
---
kind: Service
apiVersion: v1
metadata:
  name: iglu-srv
spec:
  type: NodePort
  selector:
    app: iglu
  ports:
  - protocol: TCP
    port: 8080