name: Publish images to Docker Hub

on:
  push:
    branches:
      - hackathon

jobs:
  publish:
    name: Publish images to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract release version from ref
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF##*/}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build base-alpine
      uses: docker/build-push-action@v2
      with:
        context: base-alpine
        file: base-alpine/Dockerfile
        tags: snowplow/base-alpine:dev
        push: false
